apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: sample-namespace
spec:
  forProvider:
    object:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: hello-world
  providerConfigRef:
    name: example
